### ISSUE TITLE
sbteclipse plugin doesn't download.

### ISSUE THREAD

**Issue by SoonPoong-Hong** [sbt/sbteclipse#362] opened 2018-04-23 09:07 UTC
Hey..
As below log shows, the sbteclipse plugin doesn't download.
I suspect the maven central repository delete this plugin..

Did this plugin ever works? 

===============================================================

[info] Resolving com.typesafe.sbteclipse#sbteclipse-plugin;5.2.4 ...
[warn]  module not found: com.typesafe.sbteclipse#sbteclipse-plugin;5.2.4
[warn] ==== local: tried
[warn]   C:\Users\hong\.ivy2\local\com.typesafe.sbteclipse\sbteclipse-plugin\scala_2.12\sbt_0.13\5.2.4\ivys\ivy.xml
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/com/typesafe/sbteclipse/sbteclipse-plugin_2.12_0.13/5.2.4/sbteclipse-plugin-5.2.4.pom
[warn] ==== local-preloaded-ivy: tried
[warn]   C:\Users\hong\.sbt\preloaded\com.typesafe.sbteclipse\sbteclipse-plugin\5.2.4\ivys\ivy.xml
[warn] ==== local-preloaded: tried
[warn]   file:/C:/Users/hong/.sbt/preloaded/com/typesafe/sbteclipse/sbteclipse-plugin_2.12_0.13/5.2.4/sbteclipse-plugin-5.2.4.pom
[warn] ==== Maven2 Local: tried
[warn]   file:/C:/Users/hong/.m2/repository/com/typesafe/sbteclipse/sbteclipse-plugin_2.12_0.13/5.2.4/sbteclipse-plugin-5.2.4.pom
[info] Resolving jline#jline;2.14.5 ...
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::          UNRESOLVED DEPENDENCIES         ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: com.typesafe.sbteclipse#sbteclipse-plugin;5.2.4: not found
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]
[warn]  Note: Some unresolved dependencies have extra attributes.  Check that these dependencies exist with the requested attributes.
[warn]          com.typesafe.sbteclipse:sbteclipse-plugin:5.2.4 (scalaVersion=2.12, sbtVersion=0.13)
[warn]
[warn]  Note: Unresolved dependencies path:
[warn]          com.typesafe.sbteclipse:sbteclipse-plugin:5.2.4 (scalaVersion=2.12, sbtVersion=0.13) (E:\git\hong-spark-examples\akka-sample_2\build
bt#L22-23)
[warn]            +- com.typesafe.akka.samples:akka-sample_2_2.12:16c1124c+20180423-1804
sbt.ResolveException: unresolved dependency: com.typesafe.sbteclipse#sbteclipse-plugin;5.2.4: not found

**Comment by benmccann** [comment] 2018-05-07 03:51
Closing as duplicate of https://github.com/sbt/sbteclipse/issues/341

**Closed by benmccann** 2018-05-07 03:51 UTC
